Problem statement

In the year 2000, the member states of the United Nations agreed to a set of goals to measure the progress of global development. The aim of these goals was to increase standards of living around the world by emphasizing human capital, infrastructure, and human rights.

The UN measures progress towards these goals using indicators such as percent of the population making over one dollar per day. Your task is to predict the change in these indicators one year and five years into the future. Predicting future progress will help us to understand how we achieve these goals by uncovering complex relations between these goals and other economic indicators. The UN set 2015 as the target for measurable progress. Given the data from 1972 - 2007, you need to predict a specific indicator for each of these goals in 2008 and 2012.

Import libraries

In [85]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

Load and read files

In [86]:
#read files
#Reading train file:
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/UN_TrainingSet.csv')
#Reading sample submission file:
sample = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/UN_Submission.csv')

In [87]:
train

        Unnamed: 0  ...                                        Series Name
0                0  ...  (%) Benefits held by 1st 20% population - All ...
1                1  ...  (%) Benefits held by 1st 20% population - All ...
2                2  ...  (%) Benefits held by 1st 20% population - All ...
3                4  ...             (%) Generosity of All Social Insurance
4                5  ...            (%) Generosity of All Social Protection
...            ...  ...                                                ...
195397      286113  ...  Women who believe a husband is justified in be...
195398      286114  ...  Women who believe a husband is justified in be...
195399      286115  ...  Women who believe a husband is justified in be...
195400      286116  ...  Women who believe a husband is justified in be...
195401      286117  ...  Women's share of population ages 15+ living wi...

[195402 rows x 40 columns]

Sample

This file is important! It contains the rows that you need to predict and the format for the predictions. Use the IDs in this file to extract the time series to predict from the Training Set.

In [88]:
sample

     Unnamed: 0  2008 [YR2008]  2012 [YR2012]
0           559            NaN            NaN
1           618            NaN            NaN
2           753            NaN            NaN
3          1030            NaN            NaN
4          1896            NaN            NaN
..          ...            ...            ...
732      284474            NaN            NaN
733      285340            NaN            NaN
734      285399            NaN            NaN
735      285534            NaN            NaN
736      285811            NaN            NaN

[737 rows x 3 columns]

Merge sample with train

In [89]:
Train = pd.merge(train, sample, how='right')
Train

     Unnamed: 0  1972 [YR1972]  ...  2008 [YR2008]  2012 [YR2012]
0           559            NaN  ...            NaN            NaN
1           618            NaN  ...            NaN            NaN
2           753         0.2960  ...            NaN            NaN
3          1030            NaN  ...            NaN            NaN
4          1896            NaN  ...            NaN            NaN
..          ...            ...  ...            ...            ...
732      284474            NaN  ...            NaN            NaN
733      285340            NaN  ...            NaN            NaN
734      285399            NaN  ...            NaN            NaN
735      285534         0.1087  ...            NaN            NaN
736      285811            NaN  ...            NaN            NaN

[737 rows x 42 columns]

In [90]:
train = Train.drop(['2008 [YR2008]', '2012 [YR2012]'], axis=1)
train

     Unnamed: 0  ...                                        Series Name
0           559  ...                Ensure environmental sustainability
1           618  ...  Develop a global partnership for development: ...
2           753  ...                             Reduce child mortality
3          1030  ...                                    Combat HIV/AIDS
4          1896  ...                Ensure environmental sustainability
..          ...  ...                                                ...
732      284474  ...                                    Combat HIV/AIDS
733      285340  ...                Ensure environmental sustainability
734      285399  ...  Develop a global partnership for development: ...
735      285534  ...                             Reduce child mortality
736      285811  ...                                    Combat HIV/AIDS

[737 rows x 40 columns]

Create variables

In [91]:
ID = train['Unnamed: 0']
country_name = train['Country Name']
series_code = train['Series Code']
series_name = train['Series Name']

train = train.drop(['Unnamed: 0','Country Name', 'Series Code', 'Series Name'],axis=1)
train

     1972 [YR1972]  1973 [YR1973]  ...  2006 [YR2006]  2007 [YR2007]
0              NaN            NaN  ...       0.430000         0.4650
1              NaN            NaN  ...       0.021071         0.0190
2           0.2960         0.2909  ...       0.114500         0.1115
3              NaN            NaN  ...       0.001000         0.0010
4              NaN            NaN  ...       0.962000         0.9610
..             ...            ...  ...            ...            ...
732            NaN            NaN  ...       0.136000         0.1340
733            NaN            NaN  ...       0.797000         0.7970
734            NaN            NaN  ...       0.097918         0.1085
735         0.1087         0.1083  ...       0.095800         0.0960
736            NaN            NaN  ...       0.173000         0.1640

[737 rows x 36 columns]

In [92]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 737 entries, 0 to 736
Data columns (total 36 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   1972 [YR1972]  172 non-null    float64
 1   1973 [YR1973]  170 non-null    float64
 2   1974 [YR1974]  170 non-null    float64
 3   1975 [YR1975]  179 non-null    float64
 4   1976 [YR1976]  186 non-null    float64
 5   1977 [YR1977]  192 non-null    float64
 6   1978 [YR1978]  195 non-null    float64
 7   1979 [YR1979]  200 non-null    float64
 8   1980 [YR1980]  201 non-null    float64
 9   1981 [YR1981]  213 non-null    float64
 10  1982 [YR1982]  219 non-null    float64
 11  1983 [YR1983]  219 non-null    float64
 12  1984 [YR1984]  226 non-null    float64
 13  1985 [YR1985]  229 non-null    float64
 14  1986 [YR1986]  235 non-null    float64
 15  1987 [YR1987]  227 non-null    float64
 16  1988 [YR1988]  230 non-null    float64
 17  1989 [YR1989]  231 non-null    float64
 18  1990 [YR1990]  660 non-null    float64
 19  1991 [YR1991]  504 non-null    float64
 20  1992 [YR1992]  519 non-null    float64
 21  1993 [YR1993]  533 non-null    float64
 22  1994 [YR1994]  578 non-null    float64
 23  1995 [YR1995]  626 non-null    float64
 24  1996 [YR1996]  657 non-null    float64
 25  1997 [YR1997]  660 non-null    float64
 26  1998 [YR1998]  675 non-null    float64
 27  1999 [YR1999]  701 non-null    float64
 28  2000 [YR2000]  714 non-null    float64
 29  2001 [YR2001]  713 non-null    float64
 30  2002 [YR2002]  715 non-null    float64
 31  2003 [YR2003]  713 non-null    float64
 32  2004 [YR2004]  713 non-null    float64
 33  2005 [YR2005]  726 non-null    float64
 34  2006 [YR2006]  725 non-null    float64
 35  2007 [YR2007]  737 non-null    float64
dtypes: float64(36)
memory usage: 213.0 KB

In [93]:
train.shape

(737, 36)

Impute missing values

In [94]:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer  # noqa
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer

imp = IterativeImputer(random_state=1)

train = imp.fit_transform(train)
train[train < 0] = 0
train.shape

(737, 36)

In [95]:
train

array([[0.        , 0.07481325, 0.        , ..., 0.395     , 0.43      ,
        0.465     ],
       [0.27305771, 0.17597141, 0.22986594, ..., 0.01224148, 0.02107124,
        0.019     ],
       [0.296     , 0.2909    , 0.2852    , ..., 0.1177    , 0.1145    ,
        0.1115    ],
       ...,
       [0.07749425, 0.12067247, 0.14993393, ..., 0.08015978, 0.09791841,
        0.1085    ],
       [0.1087    , 0.1083    , 0.1081    , ..., 0.0966    , 0.0958    ,
        0.096     ],
       [0.29635569, 0.16406746, 0.24595407, ..., 0.184     , 0.173     ,
        0.164     ]])

Define X, y and X_test

In [96]:
#split the dataset in two
# the last column is our label
y_train = train[:,-5:]
#drop last column of data
X_train = train[:, :-5]
#drop first colum of data
X_test = train[:,5:]
# lets have a look on the shape 
print(X_train.shape,y_train.shape,X_test.shape)

(737, 31) (737, 5) (737, 31)

In [97]:
X_train

array([[0.00000000e+00, 7.48132539e-02, 0.00000000e+00, ...,
        2.21000000e-01, 2.56000000e-01, 2.91000000e-01],
       [2.73057708e-01, 1.75971411e-01, 2.29865944e-01, ...,
        5.50137652e-02, 4.72000000e-05, 4.56000000e-05],
       [2.96000000e-01, 2.90900000e-01, 2.85200000e-01, ...,
        1.33900000e-01, 1.31000000e-01, 1.27700000e-01],
       ...,
       [7.74942520e-02, 1.20672465e-01, 1.49933927e-01, ...,
        4.01433500e-03, 7.99846000e-03, 3.99435610e-02],
       [1.08700000e-01, 1.08300000e-01, 1.08100000e-01, ...,
        1.02300000e-01, 1.01400000e-01, 1.00100000e-01],
       [2.96355687e-01, 1.64067458e-01, 2.45954066e-01, ...,
        2.57000000e-01, 2.43000000e-01, 2.28000000e-01]])

In [98]:
y_train

array([[0.325     , 0.36      , 0.395     , 0.43      , 0.465     ],
       [0.00087891, 0.00105809, 0.01224148, 0.02107124, 0.019     ],
       [0.1244    , 0.121     , 0.1177    , 0.1145    , 0.1115    ],
       ...,
       [0.06394787, 0.06564045, 0.08015978, 0.09791841, 0.1085    ],
       [0.0985    , 0.0973    , 0.0966    , 0.0958    , 0.096     ],
       [0.213     , 0.198     , 0.184     , 0.173     , 0.164     ]])

In [99]:
X_test

array([[0.02248484, 0.06614952, 0.04085576, ..., 0.395     , 0.43      ,
        0.465     ],
       [0.05795554, 0.08523337, 0.06270475, ..., 0.01224148, 0.02107124,
        0.019     ],
       [0.2683    , 0.2624    , 0.2565    , ..., 0.1177    , 0.1145    ,
        0.1115    ],
       ...,
       [0.06585548, 0.03505771, 0.00606963, ..., 0.08015978, 0.09791841,
        0.1085    ],
       [0.1077    , 0.1069    , 0.1053    , ..., 0.0966    , 0.0958    ,
        0.096     ],
       [0.29248319, 0.30760464, 0.3216563 , ..., 0.184     , 0.173     ,
        0.164     ]])

Define model

In [100]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge

model = MultiOutputRegressor(Ridge(random_state=1)).fit(X_train, y_train)
print(model.score(X_train, y_train))

0.9889457806402302

Predict on train set

In [111]:
y_pred = model.predict(X_train)
y_pred

array([[0.31445875, 0.34483806, 0.3679636 , 0.3944983 , 0.41432949],
       [0.02563175, 0.03078512, 0.03340652, 0.0418919 , 0.04394552],
       [0.12186503, 0.11808106, 0.11708665, 0.11611784, 0.12249623],
       ...,
       [0.0509829 , 0.05957215, 0.06985558, 0.08271559, 0.09093655],
       [0.11179214, 0.11700383, 0.12129979, 0.12532024, 0.13189596],
       [0.24721292, 0.24573754, 0.24135321, 0.23698611, 0.24354159]])

Predict on test set

In [116]:
prediction = model.predict(X_test)
prediction[prediction < 0] = 0
prediction

array([[0.49030123, 0.52234678, 0.54394871, 0.55959916, 0.58757275],
       [0.01248537, 0.02020568, 0.02651039, 0.03414471, 0.03644521],
       [0.10864599, 0.10693727, 0.10712049, 0.10702764, 0.11417514],
       ...,
       [0.11244768, 0.12363404, 0.13022894, 0.13555963, 0.1478745 ],
       [0.10657195, 0.11273659, 0.11759696, 0.1229994 , 0.12848685],
       [0.16269809, 0.16924315, 0.17264594, 0.17472033, 0.18384883]])

In [117]:
yr_2008 = prediction[:,0]
yr_2008

array([4.90301226e-01, 1.24853686e-02, 1.08645990e-01, 0.00000000e+00,
       1.01305371e+00, 1.26043339e-01, 2.80321281e-02, 9.56575513e-01,
       8.98204620e-01, 8.76812690e-02, 2.80520491e-02, 6.30387638e-01,
       0.00000000e+00, 5.30461741e-01, 1.69417572e-02, 1.92665784e-01,
       1.46866835e-02, 9.00290599e-01, 1.04257119e+00, 3.52319940e-01,
       5.71862772e-03, 1.04243091e+00, 2.47621343e-01, 2.54382256e-02,
       0.00000000e+00, 1.00706814e+00, 6.06881464e-02, 2.76909868e-02,
       0.00000000e+00, 1.02698245e+00, 3.18723939e-01, 9.46908534e-01,
       7.30845490e-01, 1.64871010e-02, 7.31738652e-01, 1.52732330e-02,
       9.00069821e-01, 8.44094270e-01, 1.45945876e-01, 4.83595608e-02,
       0.00000000e+00, 1.02059860e+00, 2.92813515e-01, 2.86282551e-02,
       2.95787818e-02, 3.13160385e-01, 2.04810955e-02, 8.61686663e-01,
       3.52007473e-03, 5.63551418e-02, 0.00000000e+00, 1.06367454e+00,
       6.48702473e-01, 3.17012276e-02, 2.73350924e-03, 1.06132151e+00,
       2.02757771e-01, 0.00000000e+00, 1.69209936e-02, 0.00000000e+00,
       9.52678412e-01, 7.15793859e-01, 1.56046716e-02, 1.06584101e+00,
       9.91667714e-01, 1.14730126e-01, 2.68328522e-02, 1.14604434e-02,
       7.66338290e-01, 8.01026000e-03, 1.09452912e-01, 7.05823759e-03,
       7.96287544e-01, 9.97053422e-01, 4.86103663e-02, 5.21078413e-02,
       0.00000000e+00, 8.99894088e-01, 8.85737618e-02, 5.10595909e-02,
       0.00000000e+00, 1.05139102e+00, 2.92749653e-01, 1.74555754e-02,
       1.02406332e+00, 6.39753673e-02, 7.55383149e-02, 2.59982106e-01,
       1.02073076e+00, 3.27504074e-01, 2.44906541e-02, 4.85994601e-01,
       1.76120950e-02, 1.01671704e+00, 1.06119717e+00, 3.37728007e-01,
       2.46697054e-02, 5.61542977e-01, 7.68208708e-01, 0.00000000e+00,
       1.44178439e-01, 4.08646795e-03, 7.83601287e-01, 1.92496041e-02,
       1.29140589e-01, 6.49537831e-03, 9.57988527e-01, 9.01663470e-01,
       7.31191580e-02, 3.14847303e-02, 0.00000000e+00, 1.05545669e+00,
       6.23517924e-01, 0.00000000e+00, 5.55210844e-02, 3.78660549e-03,
       7.29251481e-01, 1.63003639e-02, 1.20787407e-01, 4.70727912e-02,
       1.06334586e+00, 7.90812457e-01, 1.72787014e-02, 9.94101064e-01,
       5.33918941e-01, 6.37484648e-01, 6.97543528e-01, 0.00000000e+00,
       1.57629468e-01, 5.08177057e-01, 0.00000000e+00, 1.72834432e-01,
       2.75061106e-02, 9.29293561e-01, 1.03630844e+00, 3.94320641e-01,
       1.93851829e-02, 0.00000000e+00, 9.38213600e-01, 1.44548724e-01,
       0.00000000e+00, 2.77237070e-02, 9.91510648e-01, 9.65360991e-01,
       1.99690988e-01, 2.91478529e-02, 0.00000000e+00, 1.50917455e-02,
       9.35084665e-02, 0.00000000e+00, 4.78599759e-01, 0.00000000e+00,
       1.75087318e-01, 7.45670528e-03, 7.77223340e-01, 1.55210242e-02,
       1.20593939e-01, 2.90360344e-02, 1.02159162e+00, 2.96893666e-01,
       2.03070670e-02, 0.00000000e+00, 8.39385887e-01, 1.15061745e-02,
       1.31258650e-01, 4.00312766e-02, 1.06703909e+00, 1.04936268e+00,
       4.50432238e-01, 1.47456338e-02, 9.66015154e-01, 9.75610077e-01,
       1.24750538e-01, 1.43497285e-02, 1.65738278e-02, 0.00000000e+00,
       1.01237159e+00, 4.28872425e-01, 1.38804492e-02, 1.06334586e+00,
       5.43822618e-01, 1.31999974e-02, 9.50146182e-01, 9.70501124e-01,
       1.60177692e-02, 9.46179355e-01, 9.59453850e-03, 9.95288154e-02,
       1.67428152e-02, 4.50023907e-01, 2.48681407e-02, 9.26358693e-01,
       8.86694960e-01, 1.74128634e-01, 3.76768277e-02, 3.38448827e-03,
       8.87458994e-01, 9.28583538e-02, 3.26614570e-02, 0.00000000e+00,
       1.04699983e+00, 1.68548759e-01, 2.65600202e-02, 0.00000000e+00,
       1.01999960e+00, 9.37282703e-01, 5.06186504e-02, 2.40606072e-02,
       8.71586388e-04, 5.44961176e-03, 1.17246793e-01, 5.13367472e-02,
       4.56275740e-01, 4.08335435e-02, 6.07470020e-02, 3.49778917e-03,
       1.03216972e+00, 1.05571672e+00, 7.44900728e-01, 1.43020616e-02,
       4.43760781e-01, 0.00000000e+00, 9.11271459e-02, 1.59176772e-02,
       8.03436589e-01, 1.03446026e+00, 1.01103937e+00, 1.13191377e-01,
       3.17205101e-02, 0.00000000e+00, 9.71790542e-01, 8.98346954e-01,
       1.49556915e-02, 1.03673189e+00, 6.11570997e-01, 1.55405986e-02,
       2.88058387e-01, 9.42271826e-01, 5.15622392e-02, 8.20962467e-02,
       5.58617715e-02, 7.94994482e-01, 9.26439502e-01, 5.50811371e-02,
       8.31255599e-02, 8.15985417e-03, 1.01047189e+00, 7.91159825e-02,
       1.69123982e-02, 0.00000000e+00, 1.06767438e+00, 8.47452276e-01,
       1.54987392e-02, 7.72945252e-01, 8.54577419e-01, 3.06584580e-02,
       8.47021357e-02, 1.23813428e-02, 1.06382076e+00, 3.73624842e-01,
       1.50593022e-02, 6.82201262e-01, 1.03018578e+00, 2.65189688e-01,
       2.45973371e-02, 1.06123523e+00, 4.83531348e-01, 9.72421405e-01,
       7.09547324e-02, 4.14106129e-02, 2.58726148e-03, 7.36825714e-01,
       7.38020671e-01, 1.91539812e-03, 1.15710105e-01, 1.02695108e-02,
       1.84200415e-02, 6.76301798e-01, 1.44927765e-02, 1.49721569e-01,
       3.52571147e-02, 9.91551373e-01, 1.65556425e-01, 4.79868611e-02,
       5.60024111e-03, 6.57566035e-01, 6.73849044e-02, 8.57269282e-02,
       1.60403695e-02, 9.79463053e-01, 9.13969547e-01, 9.22258367e-02,
       3.34744525e-02, 1.39448905e-04, 8.94015082e-01, 6.78587835e-01,
       1.00817812e+00, 5.32635065e-01, 1.72377922e-02, 1.03659977e+00,
       1.41004018e-02, 9.30477174e-01, 3.18264362e-02, 7.05633666e-02,
       0.00000000e+00, 9.64663485e-01, 8.71651651e-01, 4.86238199e-02,
       4.14113593e-02, 0.00000000e+00, 1.01537624e+00, 1.01406905e-01,
       2.76328403e-02, 0.00000000e+00, 8.83344413e-01, 7.66039784e-03,
       4.73147609e-02, 1.04237527e+00, 1.06334586e+00, 6.25635309e-01,
       1.59212055e-02, 4.39575247e-01, 1.57928677e-02, 4.18837219e-01,
       1.49646702e-02, 9.92875436e-01, 2.01340211e-01, 2.92337315e-02,
       1.24850602e-02, 9.90378956e-01, 8.00873473e-01, 1.47930683e-02,
       9.88941168e-01, 1.02613452e+00, 1.84555150e-01, 3.09987178e-02,
       1.06864707e+00, 9.94795257e-01, 3.49645332e-02, 3.57954114e-02,
       6.09039045e-01, 7.60027571e-02, 1.00437731e-01, 5.75761973e-02,
       6.73115627e-01, 4.72828617e-02, 6.95520674e-02, 1.05219007e+00,
       3.93144503e-02, 9.83431908e-01, 1.03445385e+00, 8.46479255e-01,
       1.64377240e-02, 1.05476498e+00, 3.59651100e-01, 2.14896189e-02,
       1.01361699e+00, 9.19433049e-01, 1.26781425e-01, 4.05914468e-02,
       0.00000000e+00, 8.64595699e-01, 6.37438647e-01, 4.23562576e-03,
       8.95982929e-02, 0.00000000e+00, 1.04862620e+00, 6.31354801e-01,
       1.97840370e-02, 9.96947399e-01, 1.78532253e-01, 2.01357862e-02,
       7.81163827e-01, 8.54693908e-01, 2.63588212e-02, 1.34624861e-01,
       2.41436580e-01, 7.22638297e-01, 2.02278224e-02, 9.42812189e-02,
       1.09902964e-02, 2.77220051e-02, 7.16974612e-01, 1.04528613e+00,
       9.97631247e-01, 5.21321511e-01, 1.85979429e-02, 8.29354438e-01,
       1.39415169e-02, 5.09631401e-01, 1.00348767e+00, 1.05798281e+00,
       3.79814770e-01, 1.81185930e-02, 4.66619862e-01, 0.00000000e+00,
       7.00792643e-02, 0.00000000e+00, 7.97990741e-01, 0.00000000e+00,
       9.71652526e-02, 1.25735179e-01, 1.06206691e+00, 5.93762580e-01,
       1.77937761e-02, 0.00000000e+00, 1.03914383e+00, 1.61336820e-01,
       1.67373144e-02, 0.00000000e+00, 6.10041456e-01, 0.00000000e+00,
       1.51108251e-01, 5.53979988e-03, 5.00566028e-01, 1.75495737e-02,
       1.00014245e+00, 3.99346388e-02, 4.84917224e-02, 8.01381439e-01,
       4.99355705e-01, 2.47670865e-03, 1.01660990e-01, 3.73553327e-04,
       9.53768478e-01, 1.06067770e+00, 1.95482548e-01, 2.59689108e-02,
       5.68655987e-03, 9.65912150e-01, 9.82230042e-01, 2.20758457e-01,
       2.45491447e-02, 0.00000000e+00, 9.52965383e-01, 1.37419056e-01,
       5.29792421e-02, 9.79567454e-01, 9.90003177e-01, 2.18590304e-01,
       0.00000000e+00, 2.97224726e-02, 0.00000000e+00, 6.70257818e-01,
       0.00000000e+00, 1.04068035e+00, 8.33698924e-01, 1.20733682e-01,
       3.60961288e-02, 0.00000000e+00, 1.06804341e+00, 1.04372489e+00,
       3.08511540e-01, 1.86776320e-02, 9.07448392e-01, 8.62787403e-01,
       2.29856348e-01, 4.02972197e-02, 0.00000000e+00, 8.39327543e-01,
       4.84360191e-01, 0.00000000e+00, 1.12523853e-01, 1.18832534e-01,
       8.29561245e-01, 0.00000000e+00, 6.59605988e-02, 1.01869275e-03,
       9.11551951e-01, 9.19338601e-01, 4.50577855e-02, 6.79299168e-02,
       1.51415903e-01, 8.87230275e-01, 6.55514944e-03, 4.91818645e-02,
       0.00000000e+00, 1.00624272e+00, 9.29762953e-01, 1.63373939e-02,
       1.03580383e+00, 3.80817708e-01, 9.82251500e-01, 7.52945709e-01,
       1.72313861e-02, 8.93058012e-01, 3.13842648e-02, 3.37212239e-02,
       0.00000000e+00, 4.86832936e-01, 5.03782821e-01, 0.00000000e+00,
       1.43323995e-01, 2.35211703e-03, 6.38544042e-01, 5.26264365e-02,
       1.49172743e-01, 3.25817449e-02, 1.02942930e+00, 9.92656102e-01,
       9.38643399e-01, 1.49593535e-02, 9.49023776e-01, 1.31194874e-01,
       1.70056827e-02, 7.28529456e-01, 9.60417374e-01, 7.11571712e-02,
       9.94908694e-02, 0.00000000e+00, 3.40041564e-02, 1.01945188e+00,
       9.89409100e-01, 2.09105480e-01, 3.11629902e-02, 1.35007020e-03,
       3.96012194e-01, 9.54527813e-03, 7.96372155e-02, 3.85370299e-04,
       9.10301499e-01, 9.83562299e-02, 3.39306489e-02, 0.00000000e+00,
       8.96477599e-01, 2.38515899e-01, 2.58676222e-02, 0.00000000e+00,
       9.62638221e-01, 6.05020078e-02, 4.08437716e-02, 0.00000000e+00,
       1.02541344e+00, 5.26341541e-01, 1.69185617e-02, 1.05484685e+00,
       4.40459065e-01, 1.40024641e-02, 2.83047324e-01, 3.73075387e-01,
       1.88405453e-02, 1.01742460e+00, 2.92994751e-01, 2.80128467e-02,
       8.61270562e-01, 1.02609370e+00, 2.35208257e-01, 2.43145386e-02,
       7.33650643e-01, 7.02087563e-03, 8.07565970e-02, 2.38223894e-02,
       1.02440837e+00, 3.66312343e-02, 2.74649602e-02, 5.20792130e-01,
       5.44711383e-03, 9.47307550e-01, 1.53078886e-01, 7.05433859e-02,
       9.50668175e-03, 1.03371730e+00, 2.60426762e-01, 1.74132772e-02,
       7.89234316e-01, 7.50384698e-01, 6.77830970e-02, 8.43943554e-02,
       0.00000000e+00, 1.07358094e+00, 1.05794202e+00, 3.18804193e-01,
       1.57537128e-02, 1.02580451e+00, 3.94659071e-01, 2.45596231e-02,
       5.75941392e-01, 0.00000000e+00, 2.07813776e-01, 1.15968204e-02,
       7.40885522e-01, 1.36987122e-02, 6.85923113e-01, 1.75411422e-02,
       1.01648682e+00, 1.06120064e+00, 5.82903611e-01, 1.25858386e-02,
       8.62763222e-01, 1.30424090e-02, 4.53687725e-02, 6.60867888e-03,
       1.74902489e-01, 0.00000000e+00, 1.00736239e+00, 9.78429060e-01,
       7.90651317e-02, 8.63853846e-02, 1.84309575e-01, 1.18745358e-01,
       2.76966713e-02, 9.69970008e-01, 5.88661378e-01, 1.61117981e-02,
       9.85948311e-01, 9.29363408e-01, 2.96228409e-02, 2.08366763e-02,
       0.00000000e+00, 9.06880090e-01, 1.04725671e+00, 5.27764844e-01,
       1.92570332e-02, 9.54784284e-01, 9.99094585e-01, 2.95274574e-01,
       2.89178973e-02, 9.73358493e-01, 1.01445359e+00, 1.43015268e-01,
       3.29125407e-02, 6.05319332e-01, 8.92651402e-02, 9.76767746e-01,
       1.23042010e-01, 2.97071556e-02, 4.24669843e-03, 6.87632346e-01,
       3.85783302e-02, 1.35220597e-01, 2.74828530e-01, 1.03227198e+00,
       9.74721868e-01, 1.47582503e-02, 1.00687806e+00, 8.41647957e-01,
       1.63065556e-02, 9.48597732e-01, 1.18046800e-01, 2.48482295e-02,
       1.05041144e+00, 6.91518211e-01, 4.37968107e-02, 7.06407970e-02,
       0.00000000e+00, 5.68904510e-01, 5.67390314e-03, 7.56731610e-02,
       5.35584124e-02, 1.01371534e+00, 2.18429535e-01, 2.34544709e-02,
       5.94739041e-03, 6.65008459e-01, 0.00000000e+00, 6.26076309e-02,
       6.03653148e-01, 3.53952288e-02, 1.11474371e-01, 3.65205450e-02,
       1.05307314e+00, 6.50275196e-02, 2.53161486e-02, 3.35636058e-01,
       3.38503928e-02, 8.88297171e-03, 9.81179634e-01, 9.98787314e-01,
       1.55633147e-01, 2.57367836e-02, 0.00000000e+00, 1.00114676e+00,
       1.03942967e+00, 2.64835160e-01, 2.13944465e-02, 7.65232992e-01,
       4.13521849e-03, 6.74997557e-02, 1.03052076e+00, 1.52937702e-01,
       4.23090516e-02, 7.07306541e-01, 2.72555416e-02, 9.55502891e-02,
       5.71976723e-02, 9.85366038e-01, 1.02924847e+00, 5.69039113e-02,
       2.38137779e-02, 3.89518420e-03, 1.06165257e+00, 6.11040108e-01,
       1.92938186e-02, 1.00953703e+00, 8.29263394e-01, 1.69969022e-02,
       9.86331260e-01, 1.05452586e+00, 8.08491002e-01, 1.89882484e-02,
       1.04910353e+00, 3.34129476e-01, 2.32820164e-02, 4.58697521e-04,
       9.31255402e-01, 6.85287813e-02, 5.27860990e-02, 0.00000000e+00,
       9.04151392e-01, 5.96291639e-02, 2.88851970e-02, 9.83184612e-01,
       1.89681133e-01, 2.63717985e-02, 0.00000000e+00, 9.31498528e-01,
       1.97743812e-01, 3.14674176e-02, 0.00000000e+00, 3.06508478e-01,
       9.02298874e-01, 8.88149429e-01, 2.00388580e-01, 3.28295259e-02,
       5.85178779e-01, 2.94960001e-02, 7.18368729e-02, 0.00000000e+00,
       9.53146003e-01, 6.24747618e-01, 4.23294604e-02, 1.18490716e-01,
       1.33717877e-01, 8.47224088e-01, 1.12447685e-01, 1.06571952e-01,
       1.62698087e-01])

In [118]:
yr_2012 = prediction[:,4]
yr_2012

array([5.87572750e-01, 3.64452071e-02, 1.14175141e-01, 4.80731732e-03,
       1.06231957e+00, 1.85453402e-01, 5.31255462e-02, 9.87073945e-01,
       9.11066310e-01, 1.26920086e-01, 5.30260061e-02, 8.49048241e-01,
       6.87238399e-03, 5.69077093e-01, 2.86557339e-02, 2.00892741e-01,
       2.87084268e-02, 1.09178636e+00, 1.07925194e+00, 4.52722862e-01,
       1.49138059e-02, 1.08413094e+00, 3.14002953e-01, 4.18535640e-02,
       8.68143671e-03, 1.07857521e+00, 8.42156813e-02, 4.27585698e-02,
       4.80731732e-03, 1.07083516e+00, 3.74490751e-01, 9.60386132e-01,
       8.33544443e-01, 3.29926738e-02, 8.93267765e-01, 3.17663133e-02,
       9.81277777e-01, 8.92599545e-01, 1.93547698e-01, 5.61641921e-02,
       5.49198356e-03, 1.07959839e+00, 3.52143324e-01, 4.48820730e-02,
       4.38712429e-02, 3.52127312e-01, 3.63943532e-02, 9.15325794e-01,
       8.69079189e-03, 5.61806129e-02, 4.80731732e-03, 1.10439088e+00,
       8.09758884e-01, 5.04365818e-02, 1.48996535e-02, 1.09681681e+00,
       2.73723813e-01, 0.00000000e+00, 3.63047681e-02, 7.80922972e-03,
       9.69394664e-01, 8.64250468e-01, 3.19546096e-02, 1.14752889e+00,
       1.06044827e+00, 1.48607019e-01, 4.17173511e-02, 2.49271614e-02,
       8.20920764e-01, 1.31424775e-02, 1.09322619e-01, 1.99676086e-02,
       9.65974844e-01, 1.09254775e+00, 6.96409196e-02, 5.61833927e-02,
       6.11293062e-03, 9.58414125e-01, 1.36618738e-01, 5.39477915e-02,
       7.85716510e-03, 1.08895797e+00, 3.95778454e-01, 4.72855658e-02,
       1.06571974e+00, 9.03654324e-02, 9.30973003e-02, 3.06977798e-01,
       1.06731498e+00, 4.26365738e-01, 3.49935636e-02, 6.26724024e-01,
       4.03178093e-02, 1.11240764e+00, 1.09600768e+00, 4.36247321e-01,
       4.00272405e-02, 6.43779805e-01, 8.42911710e-01, 0.00000000e+00,
       1.44892865e-01, 1.14172394e-02, 8.21546829e-01, 3.86296777e-02,
       1.41486376e-01, 1.71505730e-02, 9.34545809e-01, 9.66179798e-01,
       9.46749594e-02, 4.39173384e-02, 6.70377287e-03, 1.12144909e+00,
       7.14269904e-01, 0.00000000e+00, 7.05266830e-02, 1.56162520e-02,
       7.86390624e-01, 2.60721097e-02, 1.31923432e-01, 6.62074749e-02,
       1.09892124e+00, 8.83040597e-01, 3.43452899e-02, 1.05447790e+00,
       6.72509216e-01, 7.88744123e-01, 7.37267999e-01, 0.00000000e+00,
       1.68443905e-01, 5.45003651e-01, 1.22753133e-03, 1.79831489e-01,
       4.12958730e-02, 1.13103490e+00, 1.08343060e+00, 4.68504234e-01,
       3.74462701e-02, 7.53421353e-03, 1.00712386e+00, 2.06149747e-01,
       0.00000000e+00, 3.83979862e-02, 1.03033613e+00, 1.00252665e+00,
       2.73503661e-01, 4.54903826e-02, 1.09051992e-02, 2.27692708e-02,
       1.06243518e-01, 4.80731732e-03, 5.04689704e-01, 0.00000000e+00,
       1.93673569e-01, 1.81226015e-02, 8.46042280e-01, 2.54427788e-02,
       1.40171134e-01, 3.81045412e-02, 1.06144285e+00, 3.63498150e-01,
       3.64869102e-02, 7.53534197e-03, 8.74528383e-01, 2.37918227e-02,
       1.41923577e-01, 5.28805857e-02, 1.16658780e+00, 1.08460465e+00,
       5.66964149e-01, 3.63252077e-02, 9.67879819e-01, 1.02782080e+00,
       1.66050969e-01, 4.34413823e-02, 3.22344428e-02, 4.80731732e-03,
       1.03707934e+00, 5.23280382e-01, 3.50943720e-02, 1.09892124e+00,
       6.64052865e-01, 3.38130468e-02, 9.15313398e-01, 1.15830985e+00,
       3.22693333e-02, 1.00181672e+00, 2.27716820e-02, 1.11636833e-01,
       3.05898714e-02, 5.61692923e-01, 4.18544704e-02, 1.04555755e+00,
       9.08506042e-01, 2.19128405e-01, 5.02629747e-02, 1.51589312e-02,
       9.35034411e-01, 1.35987758e-01, 4.66507119e-02, 1.08259400e-02,
       1.09231066e+00, 2.41186571e-01, 3.78566501e-02, 4.80731732e-03,
       1.12172429e+00, 9.91686986e-01, 6.09935316e-02, 3.67320248e-02,
       1.18179485e-02, 1.16441201e-02, 1.19486607e-01, 7.16203193e-02,
       4.87961266e-01, 5.87006344e-02, 5.94480008e-02, 1.47436689e-02,
       1.09073957e+00, 1.09114901e+00, 9.14676649e-01, 3.28714233e-02,
       5.14934166e-01, 7.85249371e-03, 8.12263318e-02, 2.63909760e-02,
       9.55174839e-01, 1.09103218e+00, 1.06101957e+00, 1.52029869e-01,
       4.80896942e-02, 4.80731732e-03, 1.01428854e+00, 1.07158286e+00,
       3.16299707e-02, 1.06355268e+00, 7.87038297e-01, 3.19846204e-02,
       3.60178647e-01, 1.00390132e+00, 6.34521912e-02, 9.58061012e-02,
       7.35447872e-02, 8.15428208e-01, 9.77970692e-01, 7.68229902e-02,
       8.45866413e-02, 2.06213028e-02, 1.06265686e+00, 1.07540310e-01,
       2.54160510e-02, 6.11293062e-03, 1.15313872e+00, 1.03993491e+00,
       3.23456632e-02, 8.98418232e-01, 9.28918697e-01, 5.15243106e-02,
       9.05748559e-02, 2.52875591e-02, 1.10469627e+00, 4.69558726e-01,
       3.12208274e-02, 8.00814990e-01, 1.06524265e+00, 3.41716911e-01,
       5.53924839e-02, 1.09643286e+00, 5.51935710e-01, 1.02332616e+00,
       9.56368100e-02, 5.20081691e-02, 1.44843405e-02, 8.20742807e-01,
       7.95363880e-01, 1.32422023e-02, 1.06441472e-01, 2.33976622e-02,
       1.38492537e-02, 7.51001752e-01, 2.18045070e-02, 1.52080084e-01,
       5.26030475e-02, 1.05107843e+00, 1.66510216e-01, 6.04062175e-02,
       1.94384757e-02, 6.85488359e-01, 9.34452734e-02, 9.21525535e-02,
       2.53733300e-02, 1.09258591e+00, 9.67988348e-01, 1.27048529e-01,
       4.64470760e-02, 1.09472523e-02, 9.35190513e-01, 7.72548547e-01,
       1.01138808e+00, 6.66666922e-01, 3.21046139e-02, 1.23229707e+00,
       3.06868225e-02, 9.92442151e-01, 5.58924289e-02, 7.67498531e-02,
       7.18506904e-03, 9.50738635e-01, 9.22867937e-01, 6.62513217e-02,
       5.03824024e-02, 7.64073962e-03, 1.05524027e+00, 1.35151193e-01,
       4.28074492e-02, 4.80731732e-03, 9.24131953e-01, 3.88692887e-02,
       6.26930454e-02, 1.12081317e+00, 1.09892124e+00, 7.67505377e-01,
       3.26673653e-02, 6.44310332e-01, 3.20483039e-02, 4.83474700e-01,
       3.15227265e-02, 1.02589292e+00, 2.70598571e-01, 4.44573604e-02,
       2.31158327e-02, 9.98369126e-01, 9.80675204e-01, 3.15384298e-02,
       1.06627559e+00, 1.05969685e+00, 2.62662625e-01, 4.63027902e-02,
       1.15713816e+00, 1.02840224e+00, 5.56005989e-02, 4.65494531e-02,
       6.59117453e-01, 9.37279880e-02, 1.14366101e-01, 7.44970110e-02,
       7.20774353e-01, 6.59280889e-02, 8.00717864e-02, 1.08615735e+00,
       6.73417046e-02, 9.87065611e-01, 1.08544212e+00, 9.45090165e-01,
       3.37988194e-02, 1.09014199e+00, 4.64264180e-01, 3.96045793e-02,
       1.10844334e+00, 9.76765272e-01, 1.55750278e-01, 5.09320226e-02,
       4.80731732e-03, 9.11547854e-01, 7.07147441e-01, 1.09571205e-02,
       9.05824610e-02, 6.29603270e-03, 1.08396818e+00, 8.18664440e-01,
       3.86327045e-02, 1.12867028e+00, 2.25799051e-01, 3.31236078e-02,
       7.75971600e-01, 8.90434923e-01, 3.75957935e-02, 1.63062754e-01,
       2.93658947e-01, 7.77954938e-01, 1.92214491e-02, 7.41313365e-02,
       2.26799683e-02, 4.23466805e-02, 8.33960940e-01, 1.12720450e+00,
       1.04290803e+00, 6.63649404e-01, 3.33013333e-02, 1.01021814e+00,
       3.00123028e-02, 6.15541858e-01, 1.08784590e+00, 1.09343421e+00,
       5.15795856e-01, 3.53317703e-02, 5.14830533e-01, 0.00000000e+00,
       6.18633742e-02, 1.00822416e-02, 8.83850625e-01, 3.96284621e-03,
       8.12662966e-02, 1.38440958e-01, 1.11497930e+00, 7.22286301e-01,
       3.45769301e-02, 8.44560016e-03, 1.08196866e+00, 2.20763449e-01,
       2.21489725e-02, 4.80731732e-03, 6.85527548e-01, 0.00000000e+00,
       1.45269853e-01, 1.66382790e-02, 6.37467867e-01, 3.40702624e-02,
       1.03789912e+00, 5.93705245e-02, 6.45151698e-02, 8.81510565e-01,
       5.51318013e-01, 7.50774884e-03, 1.12868938e-01, 1.14953360e-02,
       9.36945381e-01, 1.09718556e+00, 2.44956999e-01, 4.39957656e-02,
       1.77026357e-02, 9.08962996e-01, 1.03246452e+00, 2.67967691e-01,
       3.79410119e-02, 6.68727556e-03, 9.83660937e-01, 1.68956144e-01,
       7.01518679e-02, 1.05281871e+00, 1.05553440e+00, 2.88307193e-01,
       1.53738955e-03, 4.40077314e-02, 1.11247568e-02, 7.74219604e-01,
       7.62396328e-03, 1.21957865e+00, 8.92484512e-01, 1.56118737e-01,
       3.92803945e-02, 4.80731732e-03, 1.17878665e+00, 1.07917984e+00,
       3.33666916e-01, 4.88442856e-02, 9.60279859e-01, 9.06952611e-01,
       3.13553415e-01, 5.22677447e-02, 4.80731732e-03, 9.14444033e-01,
       5.28861538e-01, 3.52835969e-03, 1.00590662e-01, 1.47941207e-01,
       9.01444269e-01, 0.00000000e+00, 7.41374001e-02, 1.20741517e-02,
       9.27918611e-01, 9.83347277e-01, 6.08865268e-02, 7.98527682e-02,
       1.82511112e-01, 9.46141241e-01, 2.07194877e-02, 5.01568232e-02,
       8.63160078e-03, 1.04095387e+00, 1.11489707e+00, 3.27456594e-02,
       1.12162363e+00, 4.45713185e-01, 9.94789080e-01, 8.59929547e-01,
       3.34438468e-02, 9.41994198e-01, 5.15879228e-02, 4.71478365e-02,
       4.80731732e-03, 5.47770531e-01, 5.49107548e-01, 0.00000000e+00,
       1.14492396e-01, 1.38662139e-02, 6.88913972e-01, 6.72380683e-02,
       1.48753255e-01, 4.74917575e-02, 1.06743907e+00, 1.00706147e+00,
       1.10586365e+00, 3.10065273e-02, 1.00074581e+00, 1.94733184e-01,
       3.66847059e-02, 8.67597111e-01, 1.00189180e+00, 9.72632585e-02,
       1.06642886e-01, 4.80731732e-03, 6.30800501e-02, 1.10139718e+00,
       1.03794923e+00, 2.61276591e-01, 4.66971960e-02, 1.15024998e-02,
       4.23591144e-01, 1.45939213e-02, 9.35978069e-02, 1.19182092e-02,
       9.96933557e-01, 1.45897214e-01, 4.74409743e-02, 6.29603270e-03,
       9.44308041e-01, 2.97789780e-01, 3.27737597e-02, 7.71801164e-03,
       1.00776466e+00, 8.19719619e-02, 5.24441502e-02, 4.80731732e-03,
       1.10407477e+00, 6.74480833e-01, 3.20389403e-02, 1.09547684e+00,
       5.53582202e-01, 3.01524155e-02, 3.26960923e-01, 4.93020137e-01,
       3.45923863e-02, 1.09292271e+00, 3.90604492e-01, 4.11390746e-02,
       8.47025669e-01, 1.06595019e+00, 3.30375362e-01, 3.79908194e-02,
       7.74508868e-01, 9.77375498e-03, 7.06678525e-02, 3.25362136e-02,
       1.07177971e+00, 3.97005321e-02, 5.61082858e-02, 5.72470428e-01,
       2.93726301e-02, 1.02188238e+00, 1.80963097e-01, 7.50620189e-02,
       2.19165544e-02, 1.07492592e+00, 3.50832894e-01, 3.17092386e-02,
       8.74419940e-01, 7.96399428e-01, 1.03247806e-01, 8.60365015e-02,
       1.14062354e-02, 1.21921188e+00, 1.09335415e+00, 3.77859063e-01,
       4.22896969e-02, 1.06051202e+00, 4.94071037e-01, 4.31180546e-02,
       6.30562681e-01, 6.16741019e-03, 2.11839322e-01, 2.61322863e-02,
       9.37721885e-01, 3.02055106e-02, 8.80447110e-01, 3.84459330e-02,
       1.09557956e+00, 1.09672642e+00, 6.86383286e-01, 3.42705146e-02,
       9.32040778e-01, 2.62017182e-02, 6.35125821e-02, 1.97080950e-02,
       1.89754297e-01, 1.09822250e-02, 1.02064120e+00, 1.03066039e+00,
       1.02122533e-01, 1.08152619e-01, 2.24108844e-01, 1.03182833e-01,
       4.36717058e-02, 9.45334546e-01, 7.28551184e-01, 3.28580211e-02,
       9.98822301e-01, 9.95942821e-01, 5.01960644e-02, 3.82675943e-02,
       4.80731732e-03, 8.56154884e-01, 1.08246014e+00, 6.61711046e-01,
       3.39718011e-02, 9.15201994e-01, 1.03432769e+00, 3.59279920e-01,
       4.63323219e-02, 9.69136633e-01, 1.05774055e+00, 1.89605517e-01,
       5.34939212e-02, 6.12814444e-01, 9.49300472e-02, 1.03439974e+00,
       1.70721826e-01, 4.63432568e-02, 1.64947023e-02, 7.62959372e-01,
       5.89438356e-02, 1.63539062e-01, 3.34417198e-01, 1.15244109e+00,
       1.14849227e+00, 3.12045961e-02, 1.05538632e+00, 9.57254899e-01,
       3.29283951e-02, 9.87267039e-01, 1.68972399e-01, 3.96446097e-02,
       1.13791452e+00, 7.46347613e-01, 6.24183928e-02, 7.51278350e-02,
       5.49198356e-03, 5.90031419e-01, 1.13613473e-02, 6.72068043e-02,
       6.64500958e-02, 1.06328094e+00, 2.93118225e-01, 3.74354512e-02,
       1.71276270e-02, 7.22104791e-01, 1.33831379e-02, 5.36539099e-02,
       6.42707381e-01, 5.86610292e-02, 1.21651106e-01, 5.25940381e-02,
       1.08915435e+00, 8.99076245e-02, 4.11020733e-02, 3.92956598e-01,
       4.90652027e-02, 2.07244469e-02, 9.74124250e-01, 1.05298305e+00,
       2.03401807e-01, 4.03180543e-02, 4.80731732e-03, 9.45088720e-01,
       1.09374928e+00, 3.74612720e-01, 3.03997423e-02, 7.80306982e-01,
       9.52588923e-03, 7.93708115e-02, 1.07775230e+00, 1.76516607e-01,
       5.52743312e-02, 7.77758225e-01, 4.83309963e-02, 9.20256746e-02,
       6.07552164e-02, 1.08757493e+00, 1.08204944e+00, 8.63619933e-02,
       3.93353195e-02, 1.60817822e-02, 1.09651822e+00, 7.49186569e-01,
       3.73830575e-02, 1.05628555e+00, 1.02437723e+00, 3.38044149e-02,
       1.00918635e+00, 1.09077032e+00, 9.92211851e-01, 3.57063013e-02,
       1.08931782e+00, 4.19401946e-01, 3.98525485e-02, 1.20895020e-02,
       9.59837216e-01, 8.87045346e-02, 6.83246804e-02, 5.16153690e-03,
       9.75306140e-01, 7.27568787e-02, 4.59656525e-02, 1.08419060e+00,
       2.62313973e-01, 4.15072798e-02, 1.04127357e-02, 1.00769024e+00,
       2.55259609e-01, 4.35046618e-02, 8.90281529e-03, 3.57085436e-01,
       9.62093378e-01, 9.02036004e-01, 2.54953024e-01, 4.95358089e-02,
       5.91074139e-01, 6.30743011e-02, 8.45405012e-02, 4.80731732e-03,
       1.04429466e+00, 6.68714796e-01, 6.32839658e-02, 1.11101959e-01,
       1.51370398e-01, 8.78319217e-01, 1.47874500e-01, 1.28486852e-01,
       1.83848833e-01])

Prepare submission

In [119]:
# creating dataframe with required columns 
submission = pd.DataFrame({'Unnamed: 0':ID,'2008 [YR2008]':yr_2008,'2012 [YR2012]': yr_2012 })
# creating csv file from dataframe
submission.to_csv('submission.csv',index = False)
submission

     Unnamed: 0  2008 [YR2008]  2012 [YR2012]
0           559       0.490301       0.587573
1           618       0.012485       0.036445
2           753       0.108646       0.114175
3          1030       0.000000       0.004807
4          1896       1.013054       1.062320
..          ...            ...            ...
732      284474       0.133718       0.151370
733      285340       0.847224       0.878319
734      285399       0.112448       0.147875
735      285534       0.106572       0.128487
736      285811       0.162698       0.183849

[737 rows x 3 columns]